name: Build App

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: Waifu2x-Upscaler
  ARTIFACT_PREFIX: waifu2x-upscaler

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.runner}}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            runner: macos-latest
            platform: darwin
          - os: windows-latest
            runner: windows-latest
            platform: win32
          - os: ubuntu-latest
            runner: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Prune unneeded files
        run: npm run prune

      - name: Rebuild native modules
        run: npm run rebuild

      - name: Build app
        run: npm run build

      - name: Replace spaces
        shell: bash
        run: |
          cd build
          for f in *; do
            nf=$(echo "$f" | tr ' ' '-')
            if [ "$f" != "$nf" ]; then
              mv "$f" "$nf"
            fi
          done

      - name: Upload macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_PREFIX}}-mac
          path: |
            build/${{env.APP_NAME}}-*.dmg
            build/${{env.APP_NAME}}-*.dmg.blockmap
            build/latest-mac.yml

      - name: Upload Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_PREFIX}}-win
          path: |
            build/${{env.APP_NAME}}-*.appx
            build/${{env.APP_NAME}}-*.exe
            build/${{env.APP_NAME}}-*.exe.blockmap
            build/latest.yml

      - name: Upload Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_PREFIX}}-linux
          path: |
            build/${{env.APP_NAME}}-*.AppImage
            build/${{env.APP_NAME}}-*.AppImage.blockmap
            build/latest-linux.yml